---
# tasks file for bootcamp
    - name: Update webpage from a template
      template:
        src: template.j2
        dest: /var/www/html/index.nginx-debian.html
        owner: ubuntu
        group: ubuntu
        mode: 0774        
    - name: Get my public IP address
      uri: 
        url: "http://checkip.amazonaws.com"
        return_content: true
      register: my_public_ip
       
    - name: Output message
      debug: 
        msg: "Open http://{{ my_public_ip.content | trim }} your browser and have a fun!"

...

